# Generated by Django 6.0.4 on 2026-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
