# Generated by Django 6.0.4 on 2026-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_medicine_user_alter_medicine_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='purchase_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
