# Generated by Django 6.0.4 on 2026-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='purchase_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
